### ISSUE TITLE
[BUG] Config Saved property Pop-up color 

### ISSUE THREAD

**Issue by MaximeJoanisse** [WillTrem/UInnovate#316] opened 2024-03-22 17:49 UTC
## Description of the Bug
The pop-up for when the config is saved within the settings could confuse the user since it sometimes comes out red(maybe indicating an error)
## How To Reproduce
When changing the look-up table the pop-up for the successful change is red or blue. 
![image](https://github.com/WillTrem/UInnovate/assets/92006009/74ca47d0-6c9f-422d-8818-440e3736766f)
![image](https://github.com/WillTrem/UInnovate/assets/92006009/ead28c5a-a567-4107-a1a4-b1cb66a7a4a0)

## Expected Behavior
when the config property is saved the color of the pop-up is ideally would be green, if it fails it should stay red 

## Actual Behavior
when the config property is saved the color of the pop-up is either blue or red 

## Priority
low

**Comment by WillTrem** [comment] 2024-03-26 16:05
Re-opening as I was able to trigger it in another part of the platform. Know the cause, will be fixed with my next PR (CSV load up)

**Closed** 2024-04-06 05:12 UTC
Labels: Type: Bug, Usability
